# student-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: student-binding
  namespace: student
subjects:
- kind: ServiceAccount
  name: student # Der Name des Schülers/Studenten
  namespace: student 
roleRef:
  kind: Role
  name: student
  apiGroup: rbac.authorization.k8s.io
