apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: student
  name: student
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "persistentvolumeclaims", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update"]

########################
### Weitere Optionen ###
########################
# - apiGroups: ["apps"]
#   resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
#   verbs: ["get", "list", "watch", "create", "update", "delete"]
# - apiGroups: ["batch"]
#   resources: ["jobs", "cronjobs"]
#   verbs: ["get", "list", "watch", "create", "update", "delete"]
# - apiGroups: ["extensions"]
#   resources: ["deployments", "ingresses"]
#   verbs: ["get", "list", "watch", "create", "update", "delete"]
# - apiGroups: [""]
#   resources: ["nodes"]
#   verbs: ["none"]
