# teacher-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: teacher
  namespace: teacher
rules:
  - apiGroups:
      - "*"
    resources:
      - services
      - pods
    verbs:
      - get
      - list