# teacher-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teacher-rolebinding
  namespace: teacher
subjects:
- kind: ServiceAccount
  name: teacher
  namespace: teacher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teacher
